/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaces.IInicio;
import presetador.Controlador;

/**
 *
 * @author Carlos
 */
public class Inicio extends javax.swing.JFrame implements IInicio{

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
         listarPaquete.setAction(action);
        nuevoPaquete.addActionListener(c);
        listarSalida.addActionListener(c);
        nuevoSalida.addActionListener(c);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        nuevoPaquete = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        listarPaquete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        nuevoSalida = new javax.swing.JMenuItem();
        listarSalida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevoPaquete.setText("Paquetes");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        nuevoPaquete.add(jMenuItem1);

        listarPaquete.setText("Listar");
        nuevoPaquete.add(listarPaquete);

        jMenuBar1.add(nuevoPaquete);

        jMenu2.setText("Salidas");

        nuevoSalida.setText("Nuevo");
        nuevoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(nuevoSalida);

        listarSalida.setText("Listar");
        listarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarSalidaActionPerformed(evt);
            }
        });
        jMenu2.add(listarSalida);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoSalidaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nuevoSalidaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem listarPaquete;
    private javax.swing.JMenuItem listarSalida;
    private javax.swing.JMenu nuevoPaquete;
    private javax.swing.JMenuItem nuevoSalida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void MostrarCrearPaquete() {
       AgregarPaquete vista = new AgregarPaquete(this,true);
    }

    @Override
    public void MostrarListarPaquete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void MostrarCrearSalida() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void MostrarListarSalida() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 
    public void setControlador(Controlador c) {
        listarPaquete.addActionListener(c);
        listarPaquete.setActionCommand("LISTAR PAQUETE");
        nuevoPaquete.addActionListener(c);
        nuevoPaquete.setActionCommand("NUEVO PAQUETE");
        listarSalida.addActionListener(c);
        listarSalida.setActionCommand("LISTAR SALIDA");
        nuevoSalida.addActionListener(c);
        nuevoSalida.setActionCommand("NUEVO SALIDA");
    }
    
}
