/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaces.IListarPaquetes;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.EstadoPaquete;
import modelo.Paquete;
import presetador.PresentadorPaquete;

/**
 *
 * @author Carlos
 */
public class ListarPaquetes extends javax.swing.JDialog implements IListarPaquetes{

    /**
     * Creates new form ListarPaquetes
     */
    public ListarPaquetes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setPresentador(new PresentadorPaquete(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquetes = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnModificarEstado = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lista de Paquetes");

        tablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPaquetes);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnModificarEstado.setText("Modificar Estado");

        btnModificar.setText("Modificar Paquete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificarEstado)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarEstado)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarEstado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPaquetes;
    // End of variables declaration//GEN-END:variables

    private void setPresentador(PresentadorPaquete c) {
        btnModificarEstado.addActionListener(c);
        btnModificarEstado.setActionCommand("MODIFICAR PAQUETE ESTADO");
        btnModificar.addActionListener(c);
        btnModificar.setActionCommand("MODIFICAR PAQUETE");
        btnSalir.addActionListener(c);
        btnSalir.setActionCommand("SALIR");
        setVisible(true);
    }

    @Override
    public void configurar(ArrayList<Paquete> paquetes) {
        setLocationRelativeTo(this);
        tablaPaquetes.removeAll();
        DefaultTableModel tabla1=new DefaultTableModel();
       
        tabla1.addColumn("Descripcion");
        tabla1.addColumn("Nombre");
        tabla1.addColumn("Origen");
        tabla1.addColumn("Destino");
        tabla1.addColumn("Cant dias");
        tabla1.addColumn("Cant noche");
        tabla1.addColumn("Estado");
       
        for (Paquete paquete : paquetes) {
            
            tabla1.addRow(new Object[]{
            paquete.getDescripcion(),
            paquete.getNombre(),
            paquete.getOrigen().getNombre(),
            paquete.destinosConcatenados(),
            paquete.getCantDias(),
            paquete.getCantNoches(),
            paquete.getEstado()
            });
        }
        
        tablaPaquetes.setModel(tabla1);
    }

    @Override
    public void modificarPaquete() {
        DefaultTableModel tabla1 =(DefaultTableModel) tablaPaquetes.getModel();
         if(tablaPaquetes.getSelectedRow()!=-1){
             
            
         }
    }

    @Override
    public EstadoPaquete modificarPaqueteEstado() {
      
        
         EstadoPaquete[] estados = { EstadoPaquete.Activo, EstadoPaquete.Inactivo };
          JFrame frame = new JFrame("Cambio de estado");
          EstadoPaquete estado =  (EstadoPaquete) JOptionPane.showInputDialog(frame, 
          "What is your favorite pizza?",
          "Favorite Pizza",
        JOptionPane.QUESTION_MESSAGE, 
        null, 
        estados, 
        estados[0]);
         
         
         
         return estado;
          
    }
     @Override
    public String getPaquete() {
        String nombre="";
        if (tablaPaquetes.getSelectedRow() != -1) {
            // String estado = String.valueOf(tablaPaquetes.getValueAt(tablaPaquetes.getSelectedRow(), 5));
            nombre = String.valueOf(tablaPaquetes.getValueAt(tablaPaquetes.getSelectedRow(), 1));

        }
     
        return nombre;
    }

    @Override
    public void salir() {
        dispose();
    }
}
    

   

   
